//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./currency-converter_types');
//HELPER FUNCTIONS AND STRUCTURES

CurrencyConverter_convert_args = function(args) {
  this.value = null;
  this.currencyFrom = null;
  this.currencyTo = null;
  if (args) {
    if (args.value !== undefined && args.value !== null) {
      this.value = args.value;
    }
    if (args.currencyFrom !== undefined && args.currencyFrom !== null) {
      this.currencyFrom = args.currencyFrom;
    }
    if (args.currencyTo !== undefined && args.currencyTo !== null) {
      this.currencyTo = args.currencyTo;
    }
  }
};
CurrencyConverter_convert_args.prototype = {};
CurrencyConverter_convert_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.value = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.currencyFrom = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.currencyTo = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CurrencyConverter_convert_args.prototype.write = function(output) {
  output.writeStructBegin('CurrencyConverter_convert_args');
  if (this.value !== null && this.value !== undefined) {
    output.writeFieldBegin('value', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.value);
    output.writeFieldEnd();
  }
  if (this.currencyFrom !== null && this.currencyFrom !== undefined) {
    output.writeFieldBegin('currencyFrom', Thrift.Type.STRING, 2);
    output.writeString(this.currencyFrom);
    output.writeFieldEnd();
  }
  if (this.currencyTo !== null && this.currencyTo !== undefined) {
    output.writeFieldBegin('currencyTo', Thrift.Type.STRING, 3);
    output.writeString(this.currencyTo);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CurrencyConverter_convert_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.InvalidCurrencyException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.ex !== undefined && args.ex !== null) {
      this.ex = args.ex;
    }
  }
};
CurrencyConverter_convert_result.prototype = {};
CurrencyConverter_convert_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.DOUBLE) {
        this.success = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.InvalidCurrencyException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CurrencyConverter_convert_result.prototype.write = function(output) {
  output.writeStructBegin('CurrencyConverter_convert_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.DOUBLE, 0);
    output.writeDouble(this.success);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CurrencyConverterClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
CurrencyConverterClient.prototype = {};
CurrencyConverterClient.prototype.seqid = function() { return this._seqid; }
CurrencyConverterClient.prototype.new_seqid = function() { return this._seqid += 1; }
CurrencyConverterClient.prototype.convert = function(value, currencyFrom, currencyTo, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_convert(value, currencyFrom, currencyTo);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_convert(value, currencyFrom, currencyTo);
  }
};

CurrencyConverterClient.prototype.send_convert = function(value, currencyFrom, currencyTo) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('convert', Thrift.MessageType.CALL, this.seqid());
  var args = new CurrencyConverter_convert_args();
  args.value = value;
  args.currencyFrom = currencyFrom;
  args.currencyTo = currencyTo;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

CurrencyConverterClient.prototype.recv_convert = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new CurrencyConverter_convert_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('convert failed: unknown result');
};
CurrencyConverterProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
CurrencyConverterProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

CurrencyConverterProcessor.prototype.process_convert = function(seqid, input, output) {
  var args = new CurrencyConverter_convert_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.convert.length === 3) {
    Q.fcall(this._handler.convert, args.value, args.currencyFrom, args.currencyTo)
      .then(function(result) {
        var result = new CurrencyConverter_convert_result({success: result});
        output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InvalidCurrencyException) {
          var result = new CurrencyConverter_convert_result(err);
          output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("convert", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.convert(args.value, args.currencyFrom, args.currencyTo, function (err, result) {
      if (err == null || err instanceof ttypes.InvalidCurrencyException) {
        var result = new CurrencyConverter_convert_result((err != null ? err : {success: result}));
        output.writeMessageBegin("convert", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("convert", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

